### ISSUE TITLE
Support for non-Latin Characters for the geometric objects

### ISSUE THREAD

**Issue by AlanApter** [ibrahimsag/canberead#6]
I encountered an issue while attempting to use Yaakov Ibn Tibbon's Hebrew translation of the Elements for the project. The translation uses Hebrew characters for the figures instead of Latin characters. This would pose an issue in any non translation of Euclid's Elements that didn't use Latin characters.

##Issues Identified:

###Hardcoded Characters in Geometric Labels:

As far as I can tell, the figures in the [figures folder](src/figures) uses hardcoded characters for the geometric objects. A workaround is simply changing the hardcoded characters in the [figures folder](src/figures) on a separate branch and hosting separately. A better solution would involve allowing for internationalisation of src/figures, but I assume this would be a fair amount refactoring.

###Regex Assumes Latin Characters:

The regular expressions in src/main.js assumes Latin characters. This seems to happen in several places in [main.js](src/main.js):

[Line 403](src/main.js#L403):    
```javascript
if(/[a-zA-Z]/.test(c))
```

[Line 416](src/main.js#L416)    
```javascript
if(/[a-zA-Z]/.test(c))
```

[Line 429](src/main.js#L429)    
```javascript
if(/[a-zA-Z]/.test(c))
```

[Line 711](src/main.js#L711)        
```javascript
let nameRE = /\{([a-zA-Z]+)\}/;
```

[Line 713](src/main.js#L713)
```javascript
let overlayRE = /\{([a-zA-Z]+) ([a-z]+)( [a-zA-Z])?\}/;
```

####Proposed Solution for Regex:

I propose that [a-zA-Z] is replaced with [\p{Alphabetic}]. I've tested this locally, and it seems to work, including allowing for Hebrew characters and the interactivity works with Hebrew characters. For example, in the last example (Line 713), the code would then read:

```javascript
let overlayRE = /\{([\p{Alphabetic}]+) ([a-z]+)( [\p{Alphabetic}])?\}/u;
```

I'd be happy to open up a pull request with this change. @ibrahimsag let me know your thoughts.

**Comment by ibrahimsag** [comment]
Could there be an alternative where the markup has latin characters but the display happens through a map? That would let us share the code for figure definitions, at the cost of modifying the references in a translation.

Basically, there will be a map to hebrew characters like `{'A': 'א', 'B': 'ב', ... }`, which can probably be computed from unicode offsets, and that will be used in two places
 1. while drawing the letters on top of the figures 
 2. while turning markup like `{AB line}` into clickable html elements.

Maybe this is what you meant by internationalization, but wouldn't be all that difficult, I think. Let me know if I am missing something, otherwise I will get to implementing it soon.

**Comment by AlanApter** [comment]
Just to confirm, the mapping would be applied to each proposition - so in addition to adding he/1/1, he/1/2...etc i'll also adding he/figures/1/1 and he/figures/1/2 that will contain the mapping for the respective proposition. Because yes, that would very much work, thanks.

**Comment by ibrahimsag** [comment]
Do we need that though? since the reader is not going to see the latin letters in the `he/1/1`, I thought we would pick those letters to conform to a single mapping for all propositions.

**Comment by AlanApter** [comment]
If the mapping works perfectly, then I don't think anything would be lost (other than the historical curiosity of the choice of certain letters by Ibn Tibbon).

I do however have a concern if I miss highlighting a specific geometric object - it could end up in situation where half of the references to a line are labeled as "אב" and the other half as "גד", depending on how the mapping is applied or missed in specific instances, and this could easily confuse the reader.

I'm not sure exactly how to explain this, but as an example, imagine that we map AB to אב, and in a specific proposition (e.g. 1:1) the English calls a specific line AB and the Hebrew calls that line גד. Imagine that everything outside the braces in this example is Hebrew - if I  consistently highlight "Let {AB line} be the given finite straight-line. So it is required to construct an equilateral triangle on the straight-line {AB line}" then the text will consistently call AB אב instead of גד. However, if I miss a highlighting and I had only highlighted the first instance of AB line so that the highlighting looked like "Let {AB line} be the given finite straight-line. So it is required to construct an equilateral triangle on the straight-line גד line" then only the first {AB line} will be replaced with אב and the second reference to AB line would be גד.

If however there's a mapping for each proposition, any error would quickly become obvious as there would suddenly be Latin characters in the middle of the text - and any missed highlighting would gracefully degrade to just showing the original text instead of the interactive text.

Using a uniform mapping from Latin to Hebrew characters could simplify the implementation, so I appreciate there's a trade-off here.

**Comment by ibrahimsag** [comment]
Oh yeah, that is a good point. Thanks for taking the time to explain it.

I wanted to suggest we add some keyboard shortcut for you to use during preparation that can either:
- use a distinct color for the references
- disable the display mapping of letters so that references are in latin
so that the missing markup is easier to notice.

And if the markup is still missed, reference wouldn't have a darker color, monospace font with interactable html elements, so the reader is at least aware that there is a technical problem.

But now that I think about it more, we can just have a line at the top of the `he/1/1` file like `// א - A, ב - B, ...`  and the substitution that you would apply to the markup file can be applied programmatically. It may even be possible to share the line across propositions if convenient. And having a different map for each proposition does not feel like it would cost more.

I feel the second option is better at this point but I left the initial thoughts in case they show some options for another problem.

**Comment by ibrahimsag** [comment]
I made some changes @AlanApter 

Can have a line like ```\\ א  - A, ב - B```, anywhere on a file now. Starting with ```\\```, can contain multiple pairs around a `-`(hyphen) separated by `,`(comma). Also have the regex changes you suggested. It should point out some errors on the console as they are encountered but maybe some way to do them in bulk could be necessary. Let me know what you think.

Just to be clear, with this change, there will be non-latin characters in the curly brace markup.

**Comment by ibrahimsag** [comment]
I have also created a dropdown for picking a language when we have more than two options.

And this commit shows how one would register a new language: https://github.com/ibrahimsag/read/commit/b3852a778fa559f360d2d6d6fc45ef5296222177

**Comment by AlanApter** [comment]
Thanks for this change.

I've given it a go and I've got it working with lines, points and polygons, but for some reason I'm getting an error with highlighting for the circles - when I put the cursor over בצד or דאצ (the circles in proposition one), all the labels disappear and no highlighting appears:

![image](https://github.com/ibrahimsag/read/assets/3017506/c2fecb3b-06ce-44f7-827d-70845b0f167c)

The following appears in the javascript console:

elements.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.sub (elements.js:1:69721)
    at Object.dist (elements.js:1:69976)
    at Object.makeHighlight (elements.js:1:86057)
    at elements.js:1:81965
    at Array.forEach (<anonymous>)
    at w (elements.js:1:81935)
    at c (elements.js:1:82938)
    at elements.js:1:84276

This is the text I was using (for book 1 proposition 1):

\\ א  - A, ב - B, צ - C, ד - D

לימוד א  
לעשות על קו ישר {אב line} מוגבל המוצע משולש שווה הצלעות.

שים נקודת {א point} מרכז, ורגל השני מהמחוגה הרחק עד נקודת {ב point} ותאר עגולת {בצד circle}

וכמו כן, שים נקודת {ב point} מרכז ורגל השני מהמחוגה תרחיב עד נקודת {א point} ותאר עגולת {דאצ circle} שתחתוך עגולה הראשונה בנקודת {צ point}.

הוצא מנקודת {צ point} ב קוים א לנקודת {א point} וא לנקודת {ב point}. יהיה משולש {אבצ polygon} שווה הצלעות.

והמופת הוא הואיל וקו {אצ line} שוה לקו {אב line} כפי גדר טו. וכמו כן, קו {בצ line} גם כן שוה לקו {אב line} כפי גדר טו. אם כן כפי ידיעה א הכללית יהיה כולם שווים.

**Comment by ibrahimsag** [comment]
Yes, the circle needs a center specified. It would be like `{BCD circle A}` in the latin. The `A` isn't visible, so you can leave it as is or put `א` for completeness. Both should work. The same is needed for `arc` as well.

**Comment by ibrahimsag** [comment]
I guess you are getting the prose from some other source instead of translating the english source. It would actually be possible to find the center if not specified. I had it explicit in an attempt to keep the presenting application as simple as possible when I wasn't sure if this would work for all the book. Let me know if this becomes a nuisance for you.

**Comment by AlanApter** [comment]
Ah right, I somehow missed that. I've retested and it's working. It's probably time to close this issue.

You're right, I am getting the prose from another source, however the text I'm working from uses slightly different coordinates for the circles in proposition 1:

![image](https://github.com/ibrahimsag/read/assets/3017506/fa0d948a-ab5b-433b-a531-c43b4dade87c)

As you can see, there are four coordinates here - א ב צ ד, with the two circles sharing two points. Your text used a five coordinate system (A B C D E), with the two circles sharing only one point. I'm probably going to have to edit the text at times.
